### ISSUE TITLE
Plugin doesn't seem to work

### ISSUE THREAD

**Issue by De-Pixeled** [Reallukeisbest/meterial-you#1]

**Comment by reallukedev** [comment]
Hello, @SpiderKid07!

Could you describe your issue in more detail please?

**Comment by De-Pixeled** [comment]
Sorry for not explaining. So basically when I downloaded the file and loaded it, it only showed colors that were set from before (in my case salmon pink and it's variations) I tried changing a bunch of wallpapers but it didn't seem to update the skin 😞

**Comment by De-Pixeled** [comment]
I went through the plugins documentation and I think it works on the windows accent color if I'm not wrong. Then the change is on me sorry, I thought it extracts colors from the wallpaper. I'm really sorry for any inconvenience caused

**Comment by reallukedev** [comment]
Hello!

I'm sorry for the inconvenience. Meterial You works on the Windows accent color.

**Comment by De-Pixeled** [comment]
Hi again, I had question

Would it be possible to make the plugin so that it extracts the colour directly from the wallpaper (Just like Chameleon) and then gives out the different values with the saturation and luminance?

**Comment by reallukedev** [comment]
Hello!

You can get this capability by setting the Windows accent color setting to "Automatic" (see image below)

![image](https://github.com/Reallukeisbest/meterial-you/assets/58954397/04dcedd4-f324-4ffd-b229-4f4a10e2427d)
